### ISSUE TITLE
Assumes consecutive channels in input file

### ISSUE THREAD

**Issue by claudiucherciu** [km4sqs/ftm-convert#1]
The .csv generated by Chirp does not necessarly contain all the channels (i.e. the channels that are disabled are skipped in the exported .csv).

You can either force the renumbering of the channels, or insert empty ones when they are missing.

**Comment by claudiucherciu** [comment]
I found another example file for the FTM100D, and it seems that an empty channel (like the ones at the end of the file) can be inserted in between channels and it will be skipped by the radio.

**Comment by km4sqs** [comment]
Sorry for the delay in response: github never notified me =(

That's correct, and that's a fault of the ADMS-9 software: it doesn't like skipping channel numbers. So, for each channel number skipped, a "properly-formatted" blank line needs to be inserted.
