### ISSUE TITLE
tonefreq format is not enforced

### ISSUE THREAD

**Issue by claudiucherciu** [km4sqs/ftm-convert#2]
tonefreq should always have the first decimal. 

In my test case, I had 100 Hz in my input csv, and it was copied as-is. Only after manually changing the output file to "100.0 Hz" the file was imported by the Yaesu successfully.

**Comment by km4sqs** [comment]
Again: sorry for not responding earlier, as github didn't notify me. 

This script is meant for pulling directly from a CHIRP-exported .csv (not a user-generated .csv), and importing into ADMS-9. 

When CHIRP is populated (either through the GUI or by pulling data from RepeaterBook, etc), tonefreq will automatically be populated with a decimal place (either xx.x or xxx.x). CHIRP-exported .csv files will be in the same format:  xx.x or xxx.x

And yes you are correct: ADMS-9 is very, very particular on the format of the numbers you try to import into it.
